### ISSUE TITLE
org-ref mistakes a tag for a link

### ISSUE THREAD

**Issue by brabalan** [jkitchin/org-ref#107]
I have a diary file where one of the tags used is `ref`, for references. When org-ref is active, using this tag for a headline is problematic, as it seems to be recognized as a link. Is there a way for org-ref to recognize that this is a tag?

**Comment by jkitchin** [comment]
This seems to be a general org-mode problem if your tag name is defined as a link type. I will bring it up there.

**Comment by jkitchin** [comment]
You can probably make the ref tag last to avoid this issue.

**Comment by jkitchin** [comment]
This was confirmed to be an error in org, not org-ref. It is fixed in a future version of org. for now, probably the only fix is to make the ref tag the last one.

**Comment by brabalan** [comment]
Thanks!

**Comment by brabalan** [comment]
I just tried the fix with the current orgmode, and although I no longer have links for `file`, I still have them for `ref`:
![screen shot 2016-01-18 at 09 42 30](https://cloud.githubusercontent.com/assets/1021637/12386722/da8d6b88-bdc7-11e5-851b-e3c2a18e2467.png)

Is there something special going on in the org-ref side of things?

**Comment by jkitchin** [comment]
Is it still clickable like a tag? or a link?

What you are seeing is a result of the extra coloring I put on ref links,
which is done by an imperfect regexp.  I am not sure how to make a regexp
that excludes the starting : without adding an extra marked up space before
the links. I will look into it though. There is another approach I could
use to colorize these links that I have recently learned.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by brabalan** [comment]
It is clickable like a tag, so I guess it’s only cosmetic.

**Comment by jkitchin** [comment]
I just pushed a big rewrite of the fontification that will probably fix this.

**Comment by brabalan** [comment]
It does, thanks a lot.
