### ISSUE TITLE
Minor issue: org-ref cite- and ref-links colour issue when commenting out text

### ISSUE THREAD

**Issue by miguelazo82** [jkitchin/org-ref#118]
A small aesthetic problem which is fairly new (I think about two weeks; or maybe since migrating to MELPA):   
When I comment out a section containing any type of org-ref link  all text in this section becomes formatted in the link format; e.g. meaning all text is becoming red and underlined (which hurts in the eyes a little bit when trying to read it...).  
I am quite sure not to have changed anything in my configuration and org-ref customization is mostly default.
This does not happen with regular org-mode links. 
Thanks a lot for a great tool!

**Comment by jkitchin** [comment]
I can confirm that happens. I just pushed a fix for it.

**Comment by miguelazo82** [comment]
Kind of fixed - but now the the format of org-ref links (org-ref cite face and org-ref ref face) like colours, underline... are gone

**Comment by jkitchin** [comment]
I think I made another bug in fixing it. I pushed another fix for that this
morning.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by miguelazo82** [comment]
Update: 

I updated to  version 20160201.653 now (it apparently takes time from pushing a fix to being actually able to dowload it). 
But above problem persists: formatting lost , and table problem (should I join the two threads? - the one with the table is mine, too)
