### ISSUE TITLE
org-table with org-ref link bug

### ISSUE THREAD

**Issue by miguelazo82** [jkitchin/org-ref#119]
The push from yesterday night partially resolved an issue that I had with org-mode tables and links. I thought that it was an org-mode bug, but realize now it should have to do with org-ref: 

Links (any, org-ref and org-mode file links) were not highlighted anymore in tables. Furthermore the rescaling with TAB (and the jump to the next column) gave an error message.   Since the fix, all links are highlighted again, and the TAB "column width rescaling + jump to next column" works again for standard org-mode links, but gives an error for org-ref links.

**Comment by jkitchin** [comment]
I think this should be fixed with a push from this morning. Can you confirm?

**Comment by miguelazo82** [comment]
The problem  is with the fix from this morning; partially fixed, but only for standard links, not org-ref ones.  But at the same time there was an update of org-mode, too (and org-mode-contrib) - have you tried it with this newest version? (I suppose...)

**Comment by jkitchin** [comment]
can you post a minimal working example? I don't have any issues with the version from this morning.

Do you see any font-lock errors in the Messages?

**Comment by miguelazo82** [comment]
#+CAPTION: caption
#+LABEL: tab:table
| Testing        |   | ref:tab:table2 |   |   |
|----------------+---+---+---+---|
| TAB works fine |   | TAB not working |   |   |


#+CAPTION: Table for reference in other table...
#+LABEL: tab:table2
| Table | for | reference |

#########################
I should mention that the TAB works fine in the table before entering a reference - afterwards the whole rescaling of the table is broken - calculations still work

Yes, there is a font lock warning: today after commit
font-lock-fontify-keywords-region: Symbol's value as variable is void: at

yesterday: 
font-lock-fontify-keywords-region: Wrong type argument: listp, org-table

**Comment by miguelazo82** [comment]
Updated to newest version - now everything is fixed...

**Comment by jkitchin** [comment]
great! Thanks for letting me know.

**Comment by miguelazo82** [comment]
Thank you very much for the fix and the whole package! I am finishing to 
write my PhD thesis right now and I really depend a lot on this...

All the best,

Michael

**Comment by jkitchin** [comment]
Awesome! Good luck with the dissertation!

**Comment by miguelazo82** [comment]
Thank you!
