### ISSUE TITLE
!!! No entry found !!! when mouse hover over the "cite:xxx"

### ISSUE THREAD

**Issue by xarthurx** [jkitchin/org-ref#140]
Hi, so the problem is as the title and I've found something here:

https://lists.gnu.org/archive/html/emacs-orgmode/2015-12/msg00377.html

However, I'm using a normal link to the reftex and it still give me the error of "!!! No entry found !!!"

    (setq reftex-default-bibliography '("/cygdrive/d/Papers/bibliography/references.bib"))

I can insert with "C-c ] " from my main bibliography file, but cannot show the tool-tip. Also, if I click on the link, the minibuffer shows "wring type argument: stringp, nil

Any idea?

Thanks.

**Comment by xarthurx** [comment]
debug gives: 

#+TITLE: org-ref debug

``
org-ref: Version 0.5.0

* Variables
1. org-ref-bibliography-notes: /cygdrive/d/Documents/Dropbox (Personal)/Papers/bibliography/notes.org (exists t)
2. org-ref-default-bibliography: (/cygdrive/d/Documents/Dropbox (Personal)/Papers/bibliography/references.bib) (exists (t)) (listp t)
3. org-ref-pdf-directory: /cygdrive/d/Documents/Dropbox (Personal)/Papers/bibliography/bibtex-pdf/ (exists t)

* System
system-type: System: cygwin
system-configuration: x86_64-unknown-cygwin
window system: Window system: w32
Emacs: GNU Emacs 24.5.1 (x86_64-unknown-cygwin)
 of 2015-06-23 on desktop-new
org-version: 8.3.3

* about org-ref
org-ref installed in /home/x__x/.emacs.d/elpa/org-ref-20160214.1103/org-ref.elc.

** Dependencies
helm-bibtex /home/x__x/.emacs.d/elpa/helm-bibtex-20160210.1438/helm-bibtex.elc

* org-ref-pdf (loaded: t)
system pdftotext: /usr/bin/pdftotext
You set pdftotext-executable to pdftotext (exists: /usr/bin/pdftotext)

* org-ref-url-utils (loaded: nil)

**Comment by jkitchin** [comment]
On Mon, Feb 15, 2016 at 5:16 PM, X.Arthur <notifications@github.com> wrote:

>
I think there are problems when you have a space in the bibtex file path.
Can you try a path with no spaces?

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by xarthurx** [comment]
No difference.

Here is the new path:

* Variables
1. org-ref-bibliography-notes: /cygdrive/d/Documents/Papers/bibliography/
notes.org (exists t)
2. org-ref-default-bibliography:
(/cygdrive/d/Documents/Papers/bibliography/references.bib) (exists (t))
(listp t)
3. org-ref-pdf-directory:
/cygdrive/d/Documents/Papers/bibliography/bibtex-pdf/ (exists t)




On 15 February 2016 at 17:40, John Kitchin <notifications@github.com> wrote:

> On Mon, Feb 15, 2016 at 5:16 PM, X.Arthur <notifications@github.com>
> wrote:
>
> >
> I think there are problems when you have a space in the bibtex file path.
> Can you try a path with no spaces?
>
> John
>
> -----------------------------------
> Professor John Kitchin
> Doherty Hall A207F
> Department of Chemical Engineering
> Carnegie Mellon University
> Pittsburgh, PA 15213
> 412-268-7803
> @johnkitchin
> http://kitchingroup.cheme.cmu.edu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184426782>.
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by jkitchin** [comment]
Is it for all entries? If not what is the entry type the link is too?

On Monday, February 15, 2016, X.Arthur <notifications@github.com> wrote:

> No difference.
>
> Here is the new path:
>
> * Variables
> 1. org-ref-bibliography-notes: /cygdrive/d/Documents/Papers/bibliography/
> notes.org (exists t)
> 2. org-ref-default-bibliography:
> (/cygdrive/d/Documents/Papers/bibliography/references.bib) (exists (t))
> (listp t)
> 3. org-ref-pdf-directory:
> /cygdrive/d/Documents/Papers/bibliography/bibtex-pdf/ (exists t)
>
>
>
>
> On 15 February 2016 at 17:40, John Kitchin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > On Mon, Feb 15, 2016 at 5:16 PM, X.Arthur <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > >
> > I think there are problems when you have a space in the bibtex file path.
> > Can you try a path with no spaces?
> >
> > John
> >
> > -----------------------------------
> > Professor John Kitchin
> > Doherty Hall A207F
> > Department of Chemical Engineering
> > Carnegie Mellon University
> > Pittsburgh, PA 15213
> > 412-268-7803
> > @johnkitchin
> > http://kitchingroup.cheme.cmu.edu
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184426782>.
> >
>
>
>
> --
> MA Zhao
>
> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184428571>.
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by xarthurx** [comment]
Yes, all entries.
I put all my references in one bib file and all entries are like this...

**Comment by xarthurx** [comment]
In the reference, all entries are like:
@article{rippmann-2013-rethin,
  author =       {Matthias Rippmann and Philippe Block},
  title =        {Rethinking Structural Masonry: Unreinforced, Stone-Cut Shells},
  journal =      {Proceedings of the ICE - Construction Materials},
  volume =       166,
  number =       6,
  pages =        {378-389},
  year =         2013,
  doi =          {10.1680/coma.12.00033},
  url =          {http://dx.doi.org/10.1680/coma.12.00033},
  date_added =   {Mon Jun 1 09:11:23 2015},
}

**Comment by jkitchin** [comment]
Can you send me a small org and bib file that shows the problem for you?

On Monday, February 15, 2016, X.Arthur <notifications@github.com> wrote:

> In the reference, all entries are like:
> @article <https://github.com/article>{rippmann-2013-rethin,
> author = {Matthias Rippmann and Philippe Block},
> title = {Rethinking Structural Masonry: Unreinforced, Stone-Cut Shells},
> journal = {Proceedings of the ICE - Construction Materials},
> volume = 166,
> number = 6,
> pages = {378-389},
> year = 2013,
> doi = {10.1680/coma.12.00033},
> url = {http://dx.doi.org/10.1680/coma.12.00033},
> date_added = {Mon Jun 1 09:11:23 2015},
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184431334>.
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by xarthurx** [comment]
https://www.dropbox.com/s/x7rh3mc8yo5gpil/org-ref-test.zip?dl=0

**Comment by xarthurx** [comment]
https://www.dropbox.com/s/x7rh3mc8yo5gpil/org-ref-test.zip?dl=0

On 15 February 2016 at 18:00, John Kitchin <notifications@github.com> wrote:

> Can you send me a small org and bib file that shows the problem for you?
>
> On Monday, February 15, 2016, X.Arthur <notifications@github.com> wrote:
>
> > In the reference, all entries are like:
> > @article <https://github.com/article>{rippmann-2013-rethin,
> > author = {Matthias Rippmann and Philippe Block},
> > title = {Rethinking Structural Masonry: Unreinforced, Stone-Cut Shells},
> > journal = {Proceedings of the ICE - Construction Materials},
> > volume = 166,
> > number = 6,
> > pages = {378-389},
> > year = 2013,
> > doi = {10.1680/coma.12.00033},
> > url = {http://dx.doi.org/10.1680/coma.12.00033},
> > date_added = {Mon Jun 1 09:11:23 2015},
> > }
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184431334>.
>
> >
>
>
> --
> John
>
> -----------------------------------
> Professor John Kitchin
> Doherty Hall A207F
> Department of Chemical Engineering
> Carnegie Mellon University
> Pittsburgh, PA 15213
> 412-268-7803
> @johnkitchin
> http://kitchingroup.cheme.cmu.edu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184433160>.
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by jkitchin** [comment]
thanks. something odd does appear to be going on. I will look into it.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
I may have a solution. I pushed it to git just now. It seems to have fixed
it for me. I will check it in Melpa again tomorrow.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by xarthurx** [comment]
Hi, I found Melpa has updated, but the problem still exist.

On 15 February 2016 at 18:47, John Kitchin <notifications@github.com> wrote:

> I may have a solution. I pushed it to git just now. It seems to have fixed
> it for me. I will check it in Melpa again tomorrow.
>
> John
>
> -----------------------------------
> Professor John Kitchin
> Doherty Hall A207F
> Department of Chemical Engineering
> Carnegie Mellon University
> Pittsburgh, PA 15213
> 412-268-7803
> @johnkitchin
> http://kitchingroup.cheme.cmu.edu
>
>
> On Mon, Feb 15, 2016 at 6:38 PM, John Kitchin <jkitchin@andrew.cmu.edu>
> wrote:
>
>
> > thanks. something odd does appear to be going on. I will look into it.
> >
> > John
> >
> > -----------------------------------
> > Professor John Kitchin
> > Doherty Hall A207F
> > Department of Chemical Engineering
> > Carnegie Mellon University
> > Pittsburgh, PA 15213
> > 412-268-7803
> > @johnkitchin
> > http://kitchingroup.cheme.cmu.edu
> >
> >
> > On Mon, Feb 15, 2016 at 6:10 PM, X.Arthur <notifications@github.com>
> > wrote:
> >
> >> https://www.dropbox.com/s/x7rh3mc8yo5gpil/org-ref-test.zip?dl=0
> >>
> >> On 15 February 2016 at 18:00, John Kitchin <notifications@github.com>
> >> wrote:
> >>
> >> > Can you send me a small org and bib file that shows the problem for
> you?
> >> >
> >> > On Monday, February 15, 2016, X.Arthur <notifications@github.com>
> >> wrote:
> >> >
> >> > > In the reference, all entries are like:
> >> > > @article <https://github.com/article>{rippmann-2013-rethin,
> >> > > author = {Matthias Rippmann and Philippe Block},
> >> > > title = {Rethinking Structural Masonry: Unreinforced, Stone-Cut
> >> Shells},
> >> > > journal = {Proceedings of the ICE - Construction Materials},
> >> > > volume = 166,
> >> > > number = 6,
> >> > > pages = {378-389},
> >> > > year = 2013,
> >> > > doi = {10.1680/coma.12.00033},
> >> > > url = {http://dx.doi.org/10.1680/coma.12.00033},
> >> > > date_added = {Mon Jun 1 09:11:23 2015},
> >> > > }
> >> > >
> >> > > —
> >> > > Reply to this email directly or view it on GitHub
> >> > > <
> >> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184431334>.
> >> >
> >> > >
> >> >
> >> >
> >> > --
> >> > John
> >> >
> >> > -----------------------------------
> >> > Professor John Kitchin
> >> > Doherty Hall A207F
> >> > Department of Chemical Engineering
> >> > Carnegie Mellon University
> >> > Pittsburgh, PA 15213
> >> > 412-268-7803
> >> > @johnkitchin
> >> > http://kitchingroup.cheme.cmu.edu
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <
> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184433160
> >> >.
> >> >
> >>
> >>
> >>
> >> --
> >> MA Zhao
> >>
> >> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184435310
> >.
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184443249>.
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by jkitchin** [comment]
odd. It works fine for me with the current Melpa. Unfortunately I won't get
a chance to look at this again until the end of the day. Let me know if you
figure anything out.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by xarthurx** [comment]
I've checked that reftex works, and helm-bibtex works, so it might be the
problem of org-ref...

When click on the citation, the *Messages" shows:

org-ref-cite-candidates: Wrong type argument: stringp, nil

What commands are related in this action?

On 16 February 2016 at 08:29, John Kitchin <notifications@github.com> wrote:

> odd. It works fine for me with the current Melpa. Unfortunately I won't get
> a chance to look at this again until the end of the day. Let me know if you
> figure anything out.
>
> John
>
> -----------------------------------
> Professor John Kitchin
> Doherty Hall A207F
> Department of Chemical Engineering
> Carnegie Mellon University
> Pittsburgh, PA 15213
> 412-268-7803
> @johnkitchin
> http://kitchingroup.cheme.cmu.edu
>
>
> On Tue, Feb 16, 2016 at 8:06 AM, X.Arthur <notifications@github.com>
> wrote:
>
> > Hi, I found Melpa has updated, but the problem still exist.
> >
> >
> > On 15 February 2016 at 18:47, John Kitchin <notifications@github.com>
> > wrote:
> >
> > > I may have a solution. I pushed it to git just now. It seems to have
> > fixed
> > > it for me. I will check it in Melpa again tomorrow.
> > >
> > > John
> > >
> > > -----------------------------------
> > > Professor John Kitchin
> > > Doherty Hall A207F
> > > Department of Chemical Engineering
> > > Carnegie Mellon University
> > > Pittsburgh, PA 15213
> > > 412-268-7803
> > > @johnkitchin
> > > http://kitchingroup.cheme.cmu.edu
> > >
> > >
> > > On Mon, Feb 15, 2016 at 6:38 PM, John Kitchin <jkitchin@andrew.cmu.edu
> >
> > > wrote:
> > >
> > >
> > > > thanks. something odd does appear to be going on. I will look into
> it.
> > > >
> > > > John
> > > >
> > > > -----------------------------------
> > > > Professor John Kitchin
> > > > Doherty Hall A207F
> > > > Department of Chemical Engineering
> > > > Carnegie Mellon University
> > > > Pittsburgh, PA 15213
> > > > 412-268-7803
> > > > @johnkitchin
> > > > http://kitchingroup.cheme.cmu.edu
> > > >
> > > >
> > > > On Mon, Feb 15, 2016 at 6:10 PM, X.Arthur <notifications@github.com>
> > > > wrote:
> > > >
> > > >> https://www.dropbox.com/s/x7rh3mc8yo5gpil/org-ref-test.zip?dl=0
> > > >>
> > > >> On 15 February 2016 at 18:00, John Kitchin <
> notifications@github.com>
> > > >> wrote:
> > > >>
> > > >> > Can you send me a small org and bib file that shows the problem
> for
> > > you?
> > > >> >
> > > >> > On Monday, February 15, 2016, X.Arthur <notifications@github.com>
> > > >> wrote:
> > > >> >
> > > >> > > In the reference, all entries are like:
> > > >> > > @article <https://github.com/article>{rippmann-2013-rethin,
> > > >> > > author = {Matthias Rippmann and Philippe Block},
> > > >> > > title = {Rethinking Structural Masonry: Unreinforced, Stone-Cut
> > > >> Shells},
> > > >> > > journal = {Proceedings of the ICE - Construction Materials},
> > > >> > > volume = 166,
> > > >> > > number = 6,
> > > >> > > pages = {378-389},
> > > >> > > year = 2013,
> > > >> > > doi = {10.1680/coma.12.00033},
> > > >> > > url = {http://dx.doi.org/10.1680/coma.12.00033},
> > > >> > > date_added = {Mon Jun 1 09:11:23 2015},
> > > >> > > }
> > > >> > >
> > > >> > > —
> > > >> > > Reply to this email directly or view it on GitHub
> > > >> > > <
> > > >>
> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184431334
> > >.
> > > >> >
> > > >> > >
> > > >> >
> > > >> >
> > > >> > --
> > > >> > John
> > > >> >
> > > >> > -----------------------------------
> > > >> > Professor John Kitchin
> > > >> > Doherty Hall A207F
> > > >> > Department of Chemical Engineering
> > > >> > Carnegie Mellon University
> > > >> > Pittsburgh, PA 15213
> > > >> > 412-268-7803
> > > >> > @johnkitchin
> > > >> > http://kitchingroup.cheme.cmu.edu
> > > >> >
> > > >> > —
> > > >> > Reply to this email directly or view it on GitHub
> > > >> > <
> > > https://github.com/jkitchin/org-ref/issues/140#issuecomment-184433160
> > > >> >.
> > > >> >
> > > >>
> > > >>
> > > >>
> > > >> --
> > > >> MA Zhao
> > > >>
> > > >> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
> > > >>
> > > >> —
> > > >> Reply to this email directly or view it on GitHub
> > > >> <
> > https://github.com/jkitchin/org-ref/issues/140#issuecomment-184435310
> > > >.
> > > >>
> > > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184443249
> >.
> > >
> >
> >
> >
> > --
> > MA Zhao
> >
> > *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184676152>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184683205>.
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by jkitchin** [comment]
If you put this in the file you sent me:

bibliography:references.bib

Does it work then? There seems to be a difference between org 8.2.10 and
8.3 that I haven't tracked down yet.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
I think the issue is related to this:

#+BEGIN_SRC emacs-lisp
(org-ref-find-bibliography)
#+END_SRC

If this command is returning nil in your file, the bibliography is not
getting found, and so the key can not be located.

There are two ways to set the bibliography, one is to put the file
in org-ref-default-bibliography, and the other is a
bibliography:references.bib link in the org-file.

Can you check if that fixes it? I suggest the bibliography link.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by xarthurx** [comment]
Sorry, was in class in the morning.

If my mouse hover on the bibliography:reference.bib, the mini-buffer shows
"exists".
But when I click on it, it doesn't link to the bib file but rather a buffer
that ask me to choose one.

Yes, the command returns:

Debugger entered--Lisp error: (void-variable org-ref-find-bibliography)
  eval(org-ref-find-bibliography nil)
  eval-expression(org-ref-find-bibliography nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)

I updated quite a bunch of packages yesterday. org-ref was working all
right before then. So either the org-ref package itself or some other
packages that cause the problem.

BTW, really thank you for help tracking the error.


On 16 February 2016 at 13:46, John Kitchin <notifications@github.com> wrote:

> I think the issue is related to this:
>
> #+BEGIN_SRC emacs-lisp
> (org-ref-find-bibliography)
> #+END_SRC
>
> If this command is returning nil in your file, the bibliography is not
> getting found, and so the key can not be located.
>
> There are two ways to set the bibliography, one is to put the file
> in org-ref-default-bibliography, and the other is a
> bibliography:references.bib link in the org-file.
>
> Can you check if that fixes it? I suggest the bibliography link.
>
> John
>
> -----------------------------------
> Professor John Kitchin
> Doherty Hall A207F
> Department of Chemical Engineering
> Carnegie Mellon University
> Pittsburgh, PA 15213
> 412-268-7803
> @johnkitchin
> http://kitchingroup.cheme.cmu.edu
>
>
> On Tue, Feb 16, 2016 at 10:45 AM, John Kitchin <jkitchin@andrew.cmu.edu>
>
> wrote:
>
> > If you put this in the file you sent me:
> >
> > bibliography:references.bib
> >
> > Does it work then? There seems to be a difference between org 8.2.10 and
> > 8.3 that I haven't tracked down yet.
> >
> > John
> >
> > -----------------------------------
> > Professor John Kitchin
> > Doherty Hall A207F
> > Department of Chemical Engineering
> > Carnegie Mellon University
> > Pittsburgh, PA 15213
> > 412-268-7803
> > @johnkitchin
> > http://kitchingroup.cheme.cmu.edu
> >
> >
> > On Tue, Feb 16, 2016 at 8:29 AM, John Kitchin <jkitchin@andrew.cmu.edu>
> > wrote:
> >
> >> odd. It works fine for me with the current Melpa. Unfortunately I won't
> >> get a chance to look at this again until the end of the day. Let me
> know if
> >> you figure anything out.
> >>
> >> John
> >>
> >> -----------------------------------
> >> Professor John Kitchin
> >> Doherty Hall A207F
> >> Department of Chemical Engineering
> >> Carnegie Mellon University
> >> Pittsburgh, PA 15213
> >> 412-268-7803
> >> @johnkitchin
> >> http://kitchingroup.cheme.cmu.edu
> >>
> >>
> >> On Tue, Feb 16, 2016 at 8:06 AM, X.Arthur <notifications@github.com>
> >> wrote:
> >>
> >>> Hi, I found Melpa has updated, but the problem still exist.
> >>>
> >>>
> >>> On 15 February 2016 at 18:47, John Kitchin <notifications@github.com>
> >>> wrote:
> >>>
> >>> > I may have a solution. I pushed it to git just now. It seems to have
> >>> fixed
> >>> > it for me. I will check it in Melpa again tomorrow.
> >>> >
> >>> > John
> >>> >
> >>> > -----------------------------------
> >>> > Professor John Kitchin
> >>> > Doherty Hall A207F
> >>> > Department of Chemical Engineering
> >>> > Carnegie Mellon University
> >>> > Pittsburgh, PA 15213
> >>> > 412-268-7803
> >>> > @johnkitchin
> >>> > http://kitchingroup.cheme.cmu.edu
> >>> >
> >>> >
> >>> > On Mon, Feb 15, 2016 at 6:38 PM, John Kitchin <
> jkitchin@andrew.cmu.edu
> >>> >
> >>> > wrote:
> >>> >
> >>> >
> >>> > > thanks. something odd does appear to be going on. I will look into
> >>> it.
> >>> > >
> >>> > > John
> >>> > >
> >>> > > -----------------------------------
> >>> > > Professor John Kitchin
> >>> > > Doherty Hall A207F
> >>> > > Department of Chemical Engineering
> >>> > > Carnegie Mellon University
> >>> > > Pittsburgh, PA 15213
> >>> > > 412-268-7803
> >>> > > @johnkitchin
> >>> > > http://kitchingroup.cheme.cmu.edu
> >>> > >
> >>> > >
> >>> > > On Mon, Feb 15, 2016 at 6:10 PM, X.Arthur <
> notifications@github.com>
> >>> > > wrote:
> >>> > >
> >>> > >> https://www.dropbox.com/s/x7rh3mc8yo5gpil/org-ref-test.zip?dl=0
> >>> > >>
> >>> > >> On 15 February 2016 at 18:00, John Kitchin <
> >>> notifications@github.com>
> >>> > >> wrote:
> >>> > >>
> >>> > >> > Can you send me a small org and bib file that shows the problem
> >>> for
> >>> > you?
> >>> > >> >
> >>> > >> > On Monday, February 15, 2016, X.Arthur <
> notifications@github.com>
> >>> > >> wrote:
> >>> > >> >
> >>> > >> > > In the reference, all entries are like:
> >>> > >> > > @article <https://github.com/article>{rippmann-2013-rethin,
> >>> > >> > > author = {Matthias Rippmann and Philippe Block},
> >>> > >> > > title = {Rethinking Structural Masonry: Unreinforced,
> Stone-Cut
> >>> > >> Shells},
> >>> > >> > > journal = {Proceedings of the ICE - Construction Materials},
> >>> > >> > > volume = 166,
> >>> > >> > > number = 6,
> >>> > >> > > pages = {378-389},
> >>> > >> > > year = 2013,
> >>> > >> > > doi = {10.1680/coma.12.00033},
> >>> > >> > > url = {http://dx.doi.org/10.1680/coma.12.00033},
> >>> > >> > > date_added = {Mon Jun 1 09:11:23 2015},
> >>> > >> > > }
> >>> > >> > >
> >>> > >> > > —
> >>> > >> > > Reply to this email directly or view it on GitHub
> >>> > >> > > <
> >>> > >>
> >>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184431334
> >.
> >>> > >> >
> >>> > >> > >
> >>> > >> >
> >>> > >> >
> >>> > >> > --
> >>> > >> > John
> >>> > >> >
> >>> > >> > -----------------------------------
> >>> > >> > Professor John Kitchin
> >>> > >> > Doherty Hall A207F
> >>> > >> > Department of Chemical Engineering
> >>> > >> > Carnegie Mellon University
> >>> > >> > Pittsburgh, PA 15213
> >>> > >> > 412-268-7803
> >>> > >> > @johnkitchin
> >>> > >> > http://kitchingroup.cheme.cmu.edu
> >>> > >> >
> >>> > >> > —
> >>> > >> > Reply to this email directly or view it on GitHub
> >>> > >> > <
> >>> >
> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184433160
> >>> > >> >.
> >>> > >> >
> >>> > >>
> >>> > >>
> >>> > >>
> >>> > >> --
> >>> > >> MA Zhao
> >>> > >>
> >>> > >> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
> >>> > >>
> >>> > >> —
> >>> > >> Reply to this email directly or view it on GitHub
> >>> > >> <
> >>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184435310
> >>> > >.
> >>> > >>
> >>> > >
> >>> > >
> >>> >
> >>> > —
> >>> > Reply to this email directly or view it on GitHub
> >>> > <
> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184443249
> >>> >.
> >>> >
> >>>
> >>>
> >>>
> >>> --
> >>> MA Zhao
> >>>
> >>> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
> >>>
> >>> —
> >>> Reply to this email directly or view it on GitHub
> >>> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184676152
> >.
> >>>
> >>
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184822321>.
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by xarthurx** [comment]
And if I use the "bibliography:references.bib" method, when I click the link, Emacs returns:

Error running timer `org-ref-link-message': (file-error "Read error" "is a directory" "/home/xxx")

**Comment by xarthurx** [comment]
Oh, sorry, I didn't use the ()

So the (org-ref-find-bibliography) did return nil.

On 16 February 2016 at 13:54, X <xliotx@gmail.com> wrote:

> Sorry, was in class in the morning.
>
> If my mouse hover on the bibliography:reference.bib, the mini-buffer shows
> "exists".
> But when I click on it, it doesn't link to the bib file but rather a
> buffer that ask me to choose one.
>
> Yes, the command returns:
>
> Debugger entered--Lisp error: (void-variable org-ref-find-bibliography)
>   eval(org-ref-find-bibliography nil)
>   eval-expression(org-ref-find-bibliography nil)
>   call-interactively(eval-expression nil nil)
>   command-execute(eval-expression)
>
> I updated quite a bunch of packages yesterday. org-ref was working all
> right before then. So either the org-ref package itself or some other
> packages that cause the problem.
>
> BTW, really thank you for help tracking the error.
>
>
> On 16 February 2016 at 13:46, John Kitchin <notifications@github.com>
> wrote:
>
>> I think the issue is related to this:
>>
>> #+BEGIN_SRC emacs-lisp
>> (org-ref-find-bibliography)
>> #+END_SRC
>>
>> If this command is returning nil in your file, the bibliography is not
>> getting found, and so the key can not be located.
>>
>> There are two ways to set the bibliography, one is to put the file
>> in org-ref-default-bibliography, and the other is a
>> bibliography:references.bib link in the org-file.
>>
>> Can you check if that fixes it? I suggest the bibliography link.
>>
>> John
>>
>> -----------------------------------
>> Professor John Kitchin
>> Doherty Hall A207F
>> Department of Chemical Engineering
>> Carnegie Mellon University
>> Pittsburgh, PA 15213
>> 412-268-7803
>> @johnkitchin
>> http://kitchingroup.cheme.cmu.edu
>>
>>
>> On Tue, Feb 16, 2016 at 10:45 AM, John Kitchin <jkitchin@andrew.cmu.edu>
>>
>> wrote:
>>
>> > If you put this in the file you sent me:
>> >
>> > bibliography:references.bib
>> >
>> > Does it work then? There seems to be a difference between org 8.2.10 and
>> > 8.3 that I haven't tracked down yet.
>> >
>> > John
>> >
>> > -----------------------------------
>> > Professor John Kitchin
>> > Doherty Hall A207F
>> > Department of Chemical Engineering
>> > Carnegie Mellon University
>> > Pittsburgh, PA 15213
>> > 412-268-7803
>> > @johnkitchin
>> > http://kitchingroup.cheme.cmu.edu
>> >
>> >
>> > On Tue, Feb 16, 2016 at 8:29 AM, John Kitchin <jkitchin@andrew.cmu.edu>
>> > wrote:
>> >
>> >> odd. It works fine for me with the current Melpa. Unfortunately I won't
>> >> get a chance to look at this again until the end of the day. Let me
>> know if
>> >> you figure anything out.
>> >>
>> >> John
>> >>
>> >> -----------------------------------
>> >> Professor John Kitchin
>> >> Doherty Hall A207F
>> >> Department of Chemical Engineering
>> >> Carnegie Mellon University
>> >> Pittsburgh, PA 15213
>> >> 412-268-7803
>> >> @johnkitchin
>> >> http://kitchingroup.cheme.cmu.edu
>> >>
>> >>
>> >> On Tue, Feb 16, 2016 at 8:06 AM, X.Arthur <notifications@github.com>
>> >> wrote:
>> >>
>> >>> Hi, I found Melpa has updated, but the problem still exist.
>> >>>
>> >>>
>> >>> On 15 February 2016 at 18:47, John Kitchin <notifications@github.com>
>> >>> wrote:
>> >>>
>> >>> > I may have a solution. I pushed it to git just now. It seems to have
>> >>> fixed
>> >>> > it for me. I will check it in Melpa again tomorrow.
>> >>> >
>> >>> > John
>> >>> >
>> >>> > -----------------------------------
>> >>> > Professor John Kitchin
>> >>> > Doherty Hall A207F
>> >>> > Department of Chemical Engineering
>> >>> > Carnegie Mellon University
>> >>> > Pittsburgh, PA 15213
>> >>> > 412-268-7803
>> >>> > @johnkitchin
>> >>> > http://kitchingroup.cheme.cmu.edu
>> >>> >
>> >>> >
>> >>> > On Mon, Feb 15, 2016 at 6:38 PM, John Kitchin <
>> jkitchin@andrew.cmu.edu
>> >>> >
>> >>> > wrote:
>> >>> >
>> >>> >
>> >>> > > thanks. something odd does appear to be going on. I will look into
>> >>> it.
>> >>> > >
>> >>> > > John
>> >>> > >
>> >>> > > -----------------------------------
>> >>> > > Professor John Kitchin
>> >>> > > Doherty Hall A207F
>> >>> > > Department of Chemical Engineering
>> >>> > > Carnegie Mellon University
>> >>> > > Pittsburgh, PA 15213
>> >>> > > 412-268-7803
>> >>> > > @johnkitchin
>> >>> > > http://kitchingroup.cheme.cmu.edu
>> >>> > >
>> >>> > >
>> >>> > > On Mon, Feb 15, 2016 at 6:10 PM, X.Arthur <
>> notifications@github.com>
>> >>> > > wrote:
>> >>> > >
>> >>> > >> https://www.dropbox.com/s/x7rh3mc8yo5gpil/org-ref-test.zip?dl=0
>> >>> > >>
>> >>> > >> On 15 February 2016 at 18:00, John Kitchin <
>> >>> notifications@github.com>
>> >>> > >> wrote:
>> >>> > >>
>> >>> > >> > Can you send me a small org and bib file that shows the problem
>> >>> for
>> >>> > you?
>> >>> > >> >
>> >>> > >> > On Monday, February 15, 2016, X.Arthur <
>> notifications@github.com>
>> >>> > >> wrote:
>> >>> > >> >
>> >>> > >> > > In the reference, all entries are like:
>> >>> > >> > > @article <https://github.com/article>{rippmann-2013-rethin,
>> >>> > >> > > author = {Matthias Rippmann and Philippe Block},
>> >>> > >> > > title = {Rethinking Structural Masonry: Unreinforced,
>> Stone-Cut
>> >>> > >> Shells},
>> >>> > >> > > journal = {Proceedings of the ICE - Construction Materials},
>> >>> > >> > > volume = 166,
>> >>> > >> > > number = 6,
>> >>> > >> > > pages = {378-389},
>> >>> > >> > > year = 2013,
>> >>> > >> > > doi = {10.1680/coma.12.00033},
>> >>> > >> > > url = {http://dx.doi.org/10.1680/coma.12.00033},
>> >>> > >> > > date_added = {Mon Jun 1 09:11:23 2015},
>> >>> > >> > > }
>> >>> > >> > >
>> >>> > >> > > —
>> >>> > >> > > Reply to this email directly or view it on GitHub
>> >>> > >> > > <
>> >>> > >>
>> >>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184431334
>> >.
>> >>> > >> >
>> >>> > >> > >
>> >>> > >> >
>> >>> > >> >
>> >>> > >> > --
>> >>> > >> > John
>> >>> > >> >
>> >>> > >> > -----------------------------------
>> >>> > >> > Professor John Kitchin
>> >>> > >> > Doherty Hall A207F
>> >>> > >> > Department of Chemical Engineering
>> >>> > >> > Carnegie Mellon University
>> >>> > >> > Pittsburgh, PA 15213
>> >>> > >> > 412-268-7803
>> >>> > >> > @johnkitchin
>> >>> > >> > http://kitchingroup.cheme.cmu.edu
>> >>> > >> >
>> >>> > >> > —
>> >>> > >> > Reply to this email directly or view it on GitHub
>> >>> > >> > <
>> >>> >
>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184433160
>> >>> > >> >.
>> >>> > >> >
>> >>> > >>
>> >>> > >>
>> >>> > >>
>> >>> > >> --
>> >>> > >> MA Zhao
>> >>> > >>
>> >>> > >> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>> >>> > >>
>> >>> > >> —
>> >>> > >> Reply to this email directly or view it on GitHub
>> >>> > >> <
>> >>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184435310
>> >>> > >.
>> >>> > >>
>> >>> > >
>> >>> > >
>> >>> >
>> >>> > —
>> >>> > Reply to this email directly or view it on GitHub
>> >>> > <
>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184443249
>> >>> >.
>> >>> >
>> >>>
>> >>>
>> >>>
>> >>> --
>> >>> MA Zhao
>> >>>
>> >>> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>> >>>
>> >>> —
>> >>> Reply to this email directly or view it on GitHub
>> >>> <
>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184676152>.
>> >>>
>> >>
>> >>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184822321>.
>>
>
>
>
> --
> MA Zhao
>
> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by xarthurx** [comment]
And if I don't include "bibliography:references.bib", the command will
return the right path of my references file.
But the problem still exists.

On 16 February 2016 at 14:25, X <xliotx@gmail.com> wrote:

> Oh, sorry, I didn't use the ()
>
> So the (org-ref-find-bibliography) did return nil.
>
> On 16 February 2016 at 13:54, X <xliotx@gmail.com> wrote:
>
>> Sorry, was in class in the morning.
>>
>> If my mouse hover on the bibliography:reference.bib, the mini-buffer
>> shows "exists".
>> But when I click on it, it doesn't link to the bib file but rather a
>> buffer that ask me to choose one.
>>
>> Yes, the command returns:
>>
>> Debugger entered--Lisp error: (void-variable org-ref-find-bibliography)
>>   eval(org-ref-find-bibliography nil)
>>   eval-expression(org-ref-find-bibliography nil)
>>   call-interactively(eval-expression nil nil)
>>   command-execute(eval-expression)
>>
>> I updated quite a bunch of packages yesterday. org-ref was working all
>> right before then. So either the org-ref package itself or some other
>> packages that cause the problem.
>>
>> BTW, really thank you for help tracking the error.
>>
>>
>> On 16 February 2016 at 13:46, John Kitchin <notifications@github.com>
>> wrote:
>>
>>> I think the issue is related to this:
>>>
>>> #+BEGIN_SRC emacs-lisp
>>> (org-ref-find-bibliography)
>>> #+END_SRC
>>>
>>> If this command is returning nil in your file, the bibliography is not
>>> getting found, and so the key can not be located.
>>>
>>> There are two ways to set the bibliography, one is to put the file
>>> in org-ref-default-bibliography, and the other is a
>>> bibliography:references.bib link in the org-file.
>>>
>>> Can you check if that fixes it? I suggest the bibliography link.
>>>
>>> John
>>>
>>> -----------------------------------
>>> Professor John Kitchin
>>> Doherty Hall A207F
>>> Department of Chemical Engineering
>>> Carnegie Mellon University
>>> Pittsburgh, PA 15213
>>> 412-268-7803
>>> @johnkitchin
>>> http://kitchingroup.cheme.cmu.edu
>>>
>>>
>>> On Tue, Feb 16, 2016 at 10:45 AM, John Kitchin <jkitchin@andrew.cmu.edu>
>>>
>>> wrote:
>>>
>>> > If you put this in the file you sent me:
>>> >
>>> > bibliography:references.bib
>>> >
>>> > Does it work then? There seems to be a difference between org 8.2.10
>>> and
>>> > 8.3 that I haven't tracked down yet.
>>> >
>>> > John
>>> >
>>> > -----------------------------------
>>> > Professor John Kitchin
>>> > Doherty Hall A207F
>>> > Department of Chemical Engineering
>>> > Carnegie Mellon University
>>> > Pittsburgh, PA 15213
>>> > 412-268-7803
>>> > @johnkitchin
>>> > http://kitchingroup.cheme.cmu.edu
>>> >
>>> >
>>> > On Tue, Feb 16, 2016 at 8:29 AM, John Kitchin <jkitchin@andrew.cmu.edu
>>> >
>>> > wrote:
>>> >
>>> >> odd. It works fine for me with the current Melpa. Unfortunately I
>>> won't
>>> >> get a chance to look at this again until the end of the day. Let me
>>> know if
>>> >> you figure anything out.
>>> >>
>>> >> John
>>> >>
>>> >> -----------------------------------
>>> >> Professor John Kitchin
>>> >> Doherty Hall A207F
>>> >> Department of Chemical Engineering
>>> >> Carnegie Mellon University
>>> >> Pittsburgh, PA 15213
>>> >> 412-268-7803
>>> >> @johnkitchin
>>> >> http://kitchingroup.cheme.cmu.edu
>>> >>
>>> >>
>>> >> On Tue, Feb 16, 2016 at 8:06 AM, X.Arthur <notifications@github.com>
>>> >> wrote:
>>> >>
>>> >>> Hi, I found Melpa has updated, but the problem still exist.
>>> >>>
>>> >>>
>>> >>> On 15 February 2016 at 18:47, John Kitchin <notifications@github.com
>>> >
>>> >>> wrote:
>>> >>>
>>> >>> > I may have a solution. I pushed it to git just now. It seems to
>>> have
>>> >>> fixed
>>> >>> > it for me. I will check it in Melpa again tomorrow.
>>> >>> >
>>> >>> > John
>>> >>> >
>>> >>> > -----------------------------------
>>> >>> > Professor John Kitchin
>>> >>> > Doherty Hall A207F
>>> >>> > Department of Chemical Engineering
>>> >>> > Carnegie Mellon University
>>> >>> > Pittsburgh, PA 15213
>>> >>> > 412-268-7803
>>> >>> > @johnkitchin
>>> >>> > http://kitchingroup.cheme.cmu.edu
>>> >>> >
>>> >>> >
>>> >>> > On Mon, Feb 15, 2016 at 6:38 PM, John Kitchin <
>>> jkitchin@andrew.cmu.edu
>>> >>> >
>>> >>> > wrote:
>>> >>> >
>>> >>> >
>>> >>> > > thanks. something odd does appear to be going on. I will look
>>> into
>>> >>> it.
>>> >>> > >
>>> >>> > > John
>>> >>> > >
>>> >>> > > -----------------------------------
>>> >>> > > Professor John Kitchin
>>> >>> > > Doherty Hall A207F
>>> >>> > > Department of Chemical Engineering
>>> >>> > > Carnegie Mellon University
>>> >>> > > Pittsburgh, PA 15213
>>> >>> > > 412-268-7803
>>> >>> > > @johnkitchin
>>> >>> > > http://kitchingroup.cheme.cmu.edu
>>> >>> > >
>>> >>> > >
>>> >>> > > On Mon, Feb 15, 2016 at 6:10 PM, X.Arthur <
>>> notifications@github.com>
>>> >>> > > wrote:
>>> >>> > >
>>> >>> > >> https://www.dropbox.com/s/x7rh3mc8yo5gpil/org-ref-test.zip?dl=0
>>> >>> > >>
>>> >>> > >> On 15 February 2016 at 18:00, John Kitchin <
>>> >>> notifications@github.com>
>>> >>> > >> wrote:
>>> >>> > >>
>>> >>> > >> > Can you send me a small org and bib file that shows the
>>> problem
>>> >>> for
>>> >>> > you?
>>> >>> > >> >
>>> >>> > >> > On Monday, February 15, 2016, X.Arthur <
>>> notifications@github.com>
>>> >>> > >> wrote:
>>> >>> > >> >
>>> >>> > >> > > In the reference, all entries are like:
>>> >>> > >> > > @article <https://github.com/article>{rippmann-2013-rethin,
>>> >>> > >> > > author = {Matthias Rippmann and Philippe Block},
>>> >>> > >> > > title = {Rethinking Structural Masonry: Unreinforced,
>>> Stone-Cut
>>> >>> > >> Shells},
>>> >>> > >> > > journal = {Proceedings of the ICE - Construction Materials},
>>> >>> > >> > > volume = 166,
>>> >>> > >> > > number = 6,
>>> >>> > >> > > pages = {378-389},
>>> >>> > >> > > year = 2013,
>>> >>> > >> > > doi = {10.1680/coma.12.00033},
>>> >>> > >> > > url = {http://dx.doi.org/10.1680/coma.12.00033},
>>> >>> > >> > > date_added = {Mon Jun 1 09:11:23 2015},
>>> >>> > >> > > }
>>> >>> > >> > >
>>> >>> > >> > > —
>>> >>> > >> > > Reply to this email directly or view it on GitHub
>>> >>> > >> > > <
>>> >>> > >>
>>> >>>
>>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184431334>.
>>> >>> > >> >
>>> >>> > >> > >
>>> >>> > >> >
>>> >>> > >> >
>>> >>> > >> > --
>>> >>> > >> > John
>>> >>> > >> >
>>> >>> > >> > -----------------------------------
>>> >>> > >> > Professor John Kitchin
>>> >>> > >> > Doherty Hall A207F
>>> >>> > >> > Department of Chemical Engineering
>>> >>> > >> > Carnegie Mellon University
>>> >>> > >> > Pittsburgh, PA 15213
>>> >>> > >> > 412-268-7803
>>> >>> > >> > @johnkitchin
>>> >>> > >> > http://kitchingroup.cheme.cmu.edu
>>> >>> > >> >
>>> >>> > >> > —
>>> >>> > >> > Reply to this email directly or view it on GitHub
>>> >>> > >> > <
>>> >>> >
>>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184433160
>>> >>> > >> >.
>>> >>> > >> >
>>> >>> > >>
>>> >>> > >>
>>> >>> > >>
>>> >>> > >> --
>>> >>> > >> MA Zhao
>>> >>> > >>
>>> >>> > >> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>>> >>> > >>
>>> >>> > >> —
>>> >>> > >> Reply to this email directly or view it on GitHub
>>> >>> > >> <
>>> >>>
>>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184435310
>>> >>> > >.
>>> >>> > >>
>>> >>> > >
>>> >>> > >
>>> >>> >
>>> >>> > —
>>> >>> > Reply to this email directly or view it on GitHub
>>> >>> > <
>>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184443249
>>> >>> >.
>>> >>> >
>>> >>>
>>> >>>
>>> >>>
>>> >>> --
>>> >>> MA Zhao
>>> >>>
>>> >>> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>>> >>>
>>> >>> —
>>> >>> Reply to this email directly or view it on GitHub
>>> >>> <
>>> https://github.com/jkitchin/org-ref/issues/140#issuecomment-184676152>.
>>> >>>
>>> >>
>>> >>
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-184822321>.
>>>
>>
>>
>>
>> --
>> MA Zhao
>>
>> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>>
>
>
>
> --
> MA Zhao
>
> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by jkitchin** [comment]
I can't reliably reproduce this issue.

If I put bibliography:references.bib in the file you sent me (with references.bib in the same directory) I think everything works as expected.

Clicking on the bibliography link should open the file, or an empty file. If something else is happening, your emacs is doing something unusual. You might want to try emacs -Q and just install org-ref to see if it works like you expect.

The following text illustrates the functions that lead to the message, and might help you figure it out.


* Path to the minibuffer message
bibliography:references.bib 

This should return the active bibliography
#+BEGIN_SRC emacs-lisp
(org-ref-find-bibliography)
#+END_SRC

#+RESULTS:
| references.bib |

This should return the position of the entry with the key in the bibtex file.
#+BEGIN_SRC emacs-lisp
(org-ref-key-in-file-p "rippmann-2013-rethin" "references.bib")
#+END_SRC

#+RESULTS:
: 2

This should return a cons cell of the key and the bibtex file it is in.
#+BEGIN_SRC emacs-lisp
(org-ref-get-bibtex-key-and-file "rippmann-2013-rethin")
#+END_SRC

#+RESULTS:
: (rippmann-2013-rethin . references.bib)

This should return a citation string.
#+BEGIN_SRC emacs-lisp
(find-file "references.bib")
(goto-char (org-ref-key-in-file-p "rippmann-2013-rethin" "references.bib"))
(org-ref-bib-citation)
#+END_SRC

#+RESULTS:
: Matthias Rippmann and Philippe Block, "Rethinking Structural Masonry: Unreinforced, Stone-Cut Shells", Proceedings of the ICE - Construction Materials, 166:378-389 (2013)

This should return the citation string. This is the string used in the tooltip too.
#+BEGIN_SRC emacs-lisp
(org-ref-get-citation-string-at-point "rippmann-2013-rethin")
#+END_SRC

#+RESULTS:
: Matthias Rippmann and Philippe Block, "Rethinking Structural Masonry: Unreinforced, Stone-Cut Shells", Proceedings of the ICE - Construction Materials, 166:378-389 (2013)

**Comment by xarthurx** [comment]
Thanks.
I'll look at it and report the result.

On 17 February 2016 at 09:40, John Kitchin <notifications@github.com> wrote:

> I can't reliably reproduce this issue.
>
> If I put bibliography:references.bib in the file you sent me (with
> references.bib in the same directory) I think everything works as expected.
>
> Clicking on the bibliography link should open the file, or an empty file.
> If something else is happening, your emacs is doing something unusual. You
> might want to try emacs -Q and just install org-ref to see if it works like
> you expect.
>
> The following text illustrates the functions that lead to the message, and
> might help you figure it out.
>
>    - Path to the minibuffer message bibliography:references.bib
>
> This should return the active bibliography
> #+BEGIN_SRC emacs-lisp
> (org-ref-find-bibliography)
> #+END_SRC
>
> #+RESULTS:
> | references.bib |
>
> This should return the position of the entry with the key in the bibtex
> file.
> #+BEGIN_SRC emacs-lisp
> (org-ref-key-in-file-p "rippmann-2013-rethin" "references.bib")
> #+END_SRC
>
> #+RESULTS:
> : 2
>
> This should return a cons cell of the key and the bibtex file it is in.
> #+BEGIN_SRC emacs-lisp
> (org-ref-get-bibtex-key-and-file "rippmann-2013-rethin")
> #+END_SRC
>
> #+RESULTS:
> : (rippmann-2013-rethin . references.bib)
>
> This should return a citation string.
> #+BEGIN_SRC emacs-lisp
> (find-file "references.bib")
> (goto-char (org-ref-key-in-file-p "rippmann-2013-rethin" "references.bib"))
> (org-ref-bib-citation)
> #+END_SRC
>
> #+RESULTS:
> : Matthias Rippmann and Philippe Block, "Rethinking Structural Masonry:
> Unreinforced, Stone-Cut Shells", Proceedings of the ICE - Construction
> Materials, 166:378-389 (2013)
>
> This should return the citation string. This is the string used in the
> tooltip too.
> #+BEGIN_SRC emacs-lisp
> (org-ref-get-citation-string-at-point "rippmann-2013-rethin")
> #+END_SRC
>
> #+RESULTS:
> : Matthias Rippmann and Philippe Block, "Rethinking Structural Masonry:
> Unreinforced, Stone-Cut Shells", Proceedings of the ICE - Construction
> Materials, 166:378-389 (2013)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-185233210>.
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by xarthurx** [comment]
OK, I figured out the cause:

it is this line I put in my .emacs that cause the problem:

;; Isearch convenience, space matches anything (non-greedy) (setq
search-whitespace-regexp ".*?")

It was found here:
https://www.reddit.com/r/emacs/comments/3yxk2x/flexible_isearch_without_a_package/

Really sorry for causing the trouble and thank you for your time.


On 17 February 2016 at 09:50, X <xliotx@gmail.com> wrote:

> Thanks.
> I'll look at it and report the result.
>
> On 17 February 2016 at 09:40, John Kitchin <notifications@github.com>
> wrote:
>
>> I can't reliably reproduce this issue.
>>
>> If I put bibliography:references.bib in the file you sent me (with
>> references.bib in the same directory) I think everything works as expected.
>>
>> Clicking on the bibliography link should open the file, or an empty file.
>> If something else is happening, your emacs is doing something unusual. You
>> might want to try emacs -Q and just install org-ref to see if it works like
>> you expect.
>>
>> The following text illustrates the functions that lead to the message,
>> and might help you figure it out.
>>
>>    - Path to the minibuffer message bibliography:references.bib
>>
>> This should return the active bibliography
>> #+BEGIN_SRC emacs-lisp
>> (org-ref-find-bibliography)
>> #+END_SRC
>>
>> #+RESULTS:
>> | references.bib |
>>
>> This should return the position of the entry with the key in the bibtex
>> file.
>> #+BEGIN_SRC emacs-lisp
>> (org-ref-key-in-file-p "rippmann-2013-rethin" "references.bib")
>> #+END_SRC
>>
>> #+RESULTS:
>> : 2
>>
>> This should return a cons cell of the key and the bibtex file it is in.
>> #+BEGIN_SRC emacs-lisp
>> (org-ref-get-bibtex-key-and-file "rippmann-2013-rethin")
>> #+END_SRC
>>
>> #+RESULTS:
>> : (rippmann-2013-rethin . references.bib)
>>
>> This should return a citation string.
>> #+BEGIN_SRC emacs-lisp
>> (find-file "references.bib")
>> (goto-char (org-ref-key-in-file-p "rippmann-2013-rethin"
>> "references.bib"))
>> (org-ref-bib-citation)
>> #+END_SRC
>>
>> #+RESULTS:
>> : Matthias Rippmann and Philippe Block, "Rethinking Structural Masonry:
>> Unreinforced, Stone-Cut Shells", Proceedings of the ICE - Construction
>> Materials, 166:378-389 (2013)
>>
>> This should return the citation string. This is the string used in the
>> tooltip too.
>> #+BEGIN_SRC emacs-lisp
>> (org-ref-get-citation-string-at-point "rippmann-2013-rethin")
>> #+END_SRC
>>
>> #+RESULTS:
>> : Matthias Rippmann and Philippe Block, "Rethinking Structural Masonry:
>> Unreinforced, Stone-Cut Shells", Proceedings of the ICE - Construction
>> Materials, 166:378-389 (2013)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-185233210>.
>>
>
>
>
> --
> MA Zhao
>
> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by jkitchin** [comment]
no problem. It got me to clean a few things up and add some new tests. I have been meaning to do that for a while.

**Comment by xarthurx** [comment]
Sorry one more question:
it is possible to add entry automatically without an doi? Say some in process papers or some old scanned papers? I can find a bibtex info from google scholar, but for now I need to add entries manually.

**Comment by jkitchin** [comment]
There is no automatic way without a doi. How do you imagine that happening? The doi is used to retrieve json data from dx.doi.org to construct the bibtex entry. It is possible to get bibtex entries from arxiv and for urls, but I don't know how to get anything else.

**Comment by xarthurx** [comment]
I mean if I added the bibtex manually into the reference, is it possible to
add an entry in the note file automatically?
In a word, to extract info like below and added to note.org from bibtex:

 :PROPERTIES:
  :Custom_ID: rippmann-2011-new-desig
  :AUTHOR: Matthias Rippmann \& Philippe Block
  :JOURNAL:
  :YEAR: 2011
  :VOLUME:
  :PAGES: 181-189
  :DOI: 10.1007/978-3-642-23435-4_21
  :URL: http://dx.doi.org/10.1007/978-3-642-23435-4_21
 :END:

On 17 February 2016 at 21:40, John Kitchin <notifications@github.com> wrote:

> There is no automatic way without a doi. How do you imagine that
> happening? The doi is used to retrieve json data from dx.doi.org to
> construct the bibtex entry. It is possible to get bibtex entries from arxiv
> and for urls, but I don't know how to get anything else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/140#issuecomment-185516648>.
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by jkitchin** [comment]
try the command M-x org-ref-open-bibtex-notes

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
