### ISSUE TITLE
Can't copy formatted cite or search google scholar

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#352]
In bibtest.org (attached), when I click on the citation and then do:

     16. Copy formatted citation to clipboard

I get an error message in the minibuffer.  Also, if I do:

     8. Google Scholar

Then Google Scholar gives me this message:

      Your search - 10.1007/s00477-016-1329-0 - did not match any articles.

The DOI was plugged into the google scholar search window, which isn't how Google scholar searches.  However, it would nearly work if the DOI had been given to the ordinary Google search engine.

[bibtest.zip](https://github.com/jkitchin/org-ref/files/617125/bibtest.zip)

**Comment by jkitchin** [comment]
Thanks for reporting these. I just pushed two commits which I think fixes them. For the second one, the google scholar search is done on the title now.

**Comment by notuntoward** [comment]
Thanks -- the formatted copy now makes a nice ASCII string that I can paste into an email -- my first and foremost use.

However, Google Scholar still doesn't work for me.  I took a tour through a subset of the functions available in the hydra and found the following:

* pdf opening (C-c j p): Wrong type argument
* update (C-j U): does a reformat but ends in "no matches for "[^[:ascii:]]"  I don't know if that's expected or not
* update field (C-j u): ends with JSON readtable error
* title case (C-j T): wrong type argument...
* sentence case (C-j S): wrong type argument...
* copy key (C-j y): nothing in clipboard, key doesn't appear if I do C-y in a different buffer
* copy entry (C-j o): nothing in clipboard, key doesn't appear if I do C-y in a different buffer
* count entries (C-j F c): if there are N entries, this command returns N-1
* crossref (C-j R): goes to http://search.crossref.org/ but with a blank query string
* associate with pdf (C-j A): 
   Does this: 
   ![testbibscn_cja](https://cloud.githubusercontent.com/assets/3851891/20700654/ef328d26-b60e-11e6-8443-20fdfb2e7a4d.PNG)

    and if I select a one of the pdf files, does this:
   ![testbibscn_cja_2](https://cloud.githubusercontent.com/assets/3851891/20700701/31da443e-b60f-11e6-9272-24ca6fab82ea.PNG)

* WOS,  WOS citing (C-j w or c): opens web page, no matching items found 
* WOS related (C-j a): "no matches for "[^[:ascii:]]"
* Pubmed (C-j p): opens web page, blank search window
* Google Scholar (C-j g): opens google scholar but the Scholar search string window is blank (no title)
* [not sure what this does] (Cj p): wrong type argument

**Comment by jagrg** [comment]
@notuntoward which hydra command you are using? I cannot reproduce with `org-ref-bibtex-hydra/body`.

Also, what happens when you select "Google Scholar"?

**Comment by jkitchin** [comment]
Some of those commands only work on entries with a doi, and without one you would see some of the behavior you describe. 

copy formatted entries doesn't work well for all types of bibtex entries. It works well for articles, but maybe not inproceedings. You might check that the fields are all lower case, it seems to be sensitive to that.

It turns out Google Scholar does work with a doi sometimes. For the bibtex hydra it uses the title now with no doi.

on the copy, you have to use bibtex-yank to paste it, as it goes on the bibtex kill ring.  

For the count issue, that is an issue with `bibtex-count-entries' I guess.

It looks like the copy key issue was fixed by @jagrg (thanks!)

p should open a pdf if you have it named by the convention of key.pdf in the pdf directory. It does nothing otherwise.

the title-casing functions only work in articles right now. I don't use other types very much, so I don't know if it makes sense to do that for every type. right now they are written so you can map over all bibtex entries and change the article title case, but not for books, etc... 

On the PDF association, does the whole path to where the pdf should get copied exist?

**Comment by notuntoward** [comment]
Hi @jagrg , thanks for fixing the copy key.  I'm using  the customization org-ref-bibtex-hydra-key-binding, which I've bound to C-c j, if that matters.  

About google scholar, when I do C-c j g, a google scholar window pops up in my browser but I see the DOI still being inserted in the GS search window (which fails), even though there is a title in the bibtex entry that would work.  I see this, for example, for the Lenzi16spatTempWndProbFrcst in the attached bibfile.  For other bib entries, the GS query string is blank eg. for Gebetsberger16tricksNonHomog in the attached.  But GS searching does work for other bibtex entries eg. Becker16spatTempWndFrcstErrGrid.

[bibtest.zip](https://github.com/jkitchin/org-ref/files/621131/bibtest.zip)

Hi @jkitchin. Sorry, the C-j p "bug" was my user error:  one .emacs file, too many computers with their own paths...  

Yes, bibtex-yank was the right thing to do, and yes, the copy key issue is now fixed:  Thanks!

Google scholar is still not 100%, though, and it seems like the other search functions I mentioned have similar problems.

About the functions that don't work on certain bib entry types, would it be possible to add warning messages for us civilians?

**Comment by jagrg** [comment]
> About google scholar, when I do C-c j g, a google scholar window pops up in my browser but I see the DOI still being inserted in the GS search window (which fails), even though there is a title in the bibtex entry that would work.

What do you mean it fails? I think what you describe above is what is suppose to happen. The `org-ref-bibtex-google-scholar` command searches for the doi if the entry has one, or the title if it doesn't.

For the "Gebetsberger16tricksNonHomog" entry, the reason it fails is that `@report` is not a valid entry type AFAICT. You should you use `@techreport` instead.

**Comment by jkitchin** [comment]
I have added a entry type check to alert you to bad entry types. and a hint on how to paste the bibtex entry.
