### ISSUE TITLE
.bibtex file not being created (in org-mode) when it doesn't exist

### ISSUE THREAD

**Issue by galiantpointer** [jkitchin/org-ref#591]
_Caveat: I'm new to org-ref, so this could simply be a newbie oversight/mistake:_

According to the Youtube introduction clip (https://www.youtube.com/watch?v=2t925KRBbFc) if a bibtex file is referenced in org-mode and does not exist, the file can be clicked on, and org-ref will create a new .bibtex file for you. However, when I try this, all I get is an error in the mini buffer saying "!!! nil NOT FOUND !!!" which does not match the Youtube clip.

Does anyone else get this?

**Comment by jkitchin** [comment]
I think this is fixed now. It should appear in Melpa by the end of the day.

**Comment by galiantpointer** [comment]
Thanks John. I can confirm that the .bibtex file is being created now. I'm still getting "!!! nil NOT FOUND !!!" in the mini buffer; could this just be an artefact of my update process?

**Comment by galiantpointer** [comment]
So under what conditions would something other than `nil` be printed in the mini buffer for this same error message? The mini buffer in the YouTube clip prints "!!! manuscript.bib NOT FOUND !!!" but based on looking at the logic of `org-ref-core.el` I can't see see how I could replicate this. I was wondering if it would make more sense to print the original `bibfile` argument as part of the error string in the case that `org-ref-find-bibfile` returns `nil`?

**Comment by jkitchin** [comment]
It does make more sense to print the bibfile, and it was an easy fix to make it do that. Commit 440af8b should fix that.
